Avoid auto creation of cell hyperlink
ClosedXML/ClosedXML pull request #1185
Opened 2019-04-17 03:57 UTC by smilinger

#### What's this PR do?
Fix #1184 
#### Where should the reviewer start?
#### How should this be manually tested?
Test it in vs or powershell
#### Any background context you want to provide?

#### Screenshots (if appropriate)
#### Questions:
- Is there a blog post? 
No
- Does the knowledge base need an update?
No
- Does this add new (C#) dependencies?
No

- [ ] C# Code Review: @csreviewer
- [ ] Test Automation Review: @csreviewer

2019-04-17 08:15 UTC, igitur commented
Thanks for the PR. We appreciate all contributions. Notice that it breaks some of the unit tests, so please run the unit tests and ensure that all existing unit tests pass. You should also add your own unit test to test your own improvement. 

I'll add individual code comments in a review.

2019-04-17 08:16 UTC, igitur requested changes

2019-04-17 08:16 UTC, igitur commented on ClosedXML/Excel/Cells/XLCell.cs
> -                if (_hyperlink == null)
We definitely want to keep this. Removing this will break unit tests and people's code.

2019-04-17 08:20 UTC, igitur commented
I think the correct solution for this issue is to change a bit of the code in `XLWorkbook_Save.cs`. I think you should check whether a cell's hyperlink is valid (i.e. its internal address is not `null`) and only then generate the necessary XML.

@Pankraty Have you been following the issue ( #1184 )? I'm starting to think all of those "self-instantiating" properties should come with fail-safe mechanisms. Maybe a private boolean field to indicate whether it truly has been fully "instantiated" with subproperties. Understand what I mean?

2019-04-17 08:43 UTC, smilinger commented
Yes, you are right. I realized that right after those failed tests, then I had a look at the save functions and decided it's a little complicated for me to modify it, and like you said it's not only about hyperlinks now, I will close my PR and leave it to you guys.


-------- 原始邮件 --------
主题：Re: [ClosedXML/ClosedXML] Avoid auto creation of cell hyperlink (#1185)
发件人：Francois Botha
收件人：ClosedXML/ClosedXML
抄送：smilinger ,Author


I think the correct solution for this issue is to change a bit of the code in XLWorkbook_Save.cs. I think you should check whether a cell's hyperlink is valid (i.e. its internal address is not null) and only then generate the necessary XML.

@Pankraty<https://github.com/Pankraty> Have you been following the issue ( #1184<https://github.com/ClosedXML/ClosedXML/issues/1184> )? I'm starting to think all of those "self-instantiating" properties should come with fail-safe mechanisms. Maybe a private boolean field to indicate whether it truly has been fully "instantiated" with subproperties. Understand what I mean?

―
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/ClosedXML/ClosedXML/pull/1185#issuecomment-483986535>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AEfwDIWbft8HHWf_F7bXRmXjpPPNVb8rks5vhtlcgaJpZM4c0JOs>.

2019-04-17 10:00 UTC, Pankraty commented
@igitur, this makes a perfect sense. I can't check the code right now but I got your point and agree with you.

2019-04-21 13:51 UTC, igitur commented
Properties that need private fields to indicate full initialisation:
- Hyperlink
- Comment
- RichText
- DataValidation

2022-06-29 11:30 UTC, igitur commented
Fixed in #1396

2022-06-29 11:30 UTC, closed without merging