Remove obsolete code from GenerateCalculationChainPartContent (#1280)
ClosedXML/ClosedXML pull request #1284
Opened 2019-08-31 12:17 UTC by Pankraty

Here I remove filling `cellsWithoutFormulas` collection which has not been used for last two years (from 56db35624eeaae2ec794e6b4b131f0a22f838a4c). This lowers the memory usage (~147 MB on the test file from #1280) and should speed up saving thanks to removing multiple `c.Address.ToStringRelative()` calls.

Better see the diff in "ignore spaces" mode.

2019-09-09 21:27 UTC, InusualZ commented
Is this PR it's in a merge-able state? I would like to use it on my local copy. Not saying this to rush things or anything.

Another question. Do you guys have a communication method? I would like to ask some trivial question, not worthy of a github issue, just like this one :)

2019-09-11 14:04 UTC, igitur commented
@InusualZ It's mergeable, but hasn't been reviewed.

Please log an issue for any trivial question. Others might benefit from it.

2020-02-11 07:05 UTC, igitur commented on ClosedXML/Excel/XLWorkbook_Save.cs
> +                if (!xlCell.StyleValue.IncludeQuotePrefix && xlCell.InnerText.Length == 0)
Looks like there are some other places too, e.g. https://github.com/ClosedXML/ClosedXML/blob/fb542bfa6d7a8a65a616a11c8b8e1df384ff6316/ClosedXML/Excel/XLWorkbook_Save.cs#L959 , right?

2020-02-11 08:08 UTC, igitur requested changes
Let me know if you agree with just that one extra adjustment.

2020-02-25 07:55 UTC, Pankraty commented on ClosedXML/Excel/XLWorkbook_Save.cs
> +                if (!xlCell.StyleValue.IncludeQuotePrefix && xlCell.InnerText.Length == 0)
Agree. Fixed.

2020-03-02 12:23 UTC, igitur approved these changes

2020-03-02 12:23 UTC, merged