Added GrowRow()
ClosedXML/ClosedXML pull request #1301
Opened 2019-10-28 23:17 UTC by carlosproiete

Hello! I added a new method called GrowRow(int), to grow the selection not only in both ways, but downwards.

2020-02-11 08:40 UTC, igitur commented
Please add some unit tests. Look for the unit tests for `Grow()` for an example.

2020-09-21 18:13 UTC, igitur requested changes
Please also add unit tests.

2020-09-21 18:13 UTC, igitur commented on ClosedXML/Excel/Ranges/IXLRangeBase.cs
> +        IXLRangeBase GrowRow(Int32 growRowCount);
I think `GrowDown` is a better name. Agree?

2023-12-27 10:23 UTC, closed without merging

2023-12-27 10:23 UTC, jahav commented
Closing without merge.

I don't think it's worth expanding API surface for this. The proposed method could easily be implemented in client code as an extension method. Also, there are no unit tests and semantic is unclear, doc says that it expands the current range, but method returns a new one without expanding the original one.