Implement DATEDIF function
ClosedXML/ClosedXML pull request #1551
Opened 2020-11-02 15:10 UTC by MiNGRotten

Implement DATEDIF function for calculate difference between two dates.
MS specs: https://support.microsoft.com/en-us/office/datedif-function-25dba1a4-2812-480b-84dd-8b32a451b35c

2020-11-20 09:56 UTC, igitur commented
I refactored the method. There were some edge cases that weren't calculated correctly.

2020-11-21 12:52 UTC, Pankraty commented on ClosedXML/Excel/CalcEngine/Functions/DateAndTime.cs
> +                "M" => Math.Truncate((endDate.Year - startDate.Year) * 12d + endDate.Month - startDate.Month),
Nope.
![image](https://user-images.githubusercontent.com/19576939/99877771-e4d68280-2c19-11eb-812e-6f54faddcf73.png)

2020-11-21 12:53 UTC, Pankraty requested changes
Not all edge cases have been covered, apparently

2020-11-23 07:05 UTC, igitur commented on ClosedXML/Excel/CalcEngine/Functions/DateAndTime.cs
> +                "M" => Math.Truncate((endDate.Year - startDate.Year) * 12d + endDate.Month - startDate.Month),
Good catch. Fixed.

2020-11-23 07:05 UTC, igitur commented
I'll squash and rebase after final approval.

2020-11-23 09:14 UTC, Pankraty commented on ClosedXML/Excel/CalcEngine/Functions/DateAndTime.cs
> +                "D" => Math.Truncate(endDate.Subtract(startDate).TotalDays),
Nope. 
![image](https://user-images.githubusercontent.com/19576939/99943763-410ce400-2d8b-11eb-999b-d584caf56510.png)

This should do the trick:
```suggestion
                "D" => Math.Truncate(endDate.Date.Subtract(startDate.Date).TotalDays),
```

Or even without `Math.Truncate` - CLR does not seem to care about daylight saving time and returns whole numbers anyway.

2020-11-23 10:36 UTC, igitur commented
Now I understand why Microsoft discourages use of this function ;-)

2020-12-16 08:59 UTC, merged